"""empty message

Revision ID: 19639257a53f
Revises: 
Create Date: 2020-02-09 17:37:16.796818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19639257a53f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theater',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seatings_row',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theater_id', sa.Integer(), nullable=False),
    sa.Column('row_name', sa.String(length=300), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('is_aisle', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['theater_id'], ['theater.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seatings_row')
    op.drop_table('theater')
    # ### end Alembic commands ###
