"""empty message

Revision ID: 348e8bdff5de
Revises: 19639257a53f
Create Date: 2020-02-21 08:07:36.720220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348e8bdff5de'
down_revision = '19639257a53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seatings_row', sa.Column('slug', sa.String(length=300)))
    op.add_column('theater', sa.Column('slug', sa.String(length=300)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theater', 'slug')
    op.drop_column('seatings_row', 'slug')
    # ### end Alembic commands ###
