"""empty message

Revision ID: c7adfb61fe72
Revises: 348e8bdff5de
Create Date: 2020-03-02 22:47:47.233454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7adfb61fe72'
down_revision = '348e8bdff5de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screen',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=True),
    sa.Column('theater_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theater_id'], ['theater.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('seatings_row', sa.Column('screen_id', sa.Integer(), nullable=False))
    op.drop_constraint('seatings_row_theater_id_fkey', 'seatings_row', type_='foreignkey')
    op.create_foreign_key(None, 'seatings_row', 'screen', ['screen_id'], ['id'])
    op.drop_column('seatings_row', 'theater_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seatings_row', sa.Column('theater_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'seatings_row', type_='foreignkey')
    op.create_foreign_key('seatings_row_theater_id_fkey', 'seatings_row', 'theater', ['theater_id'], ['id'])
    op.drop_column('seatings_row', 'screen_id')
    op.drop_table('screen')
    # ### end Alembic commands ###
